mon_income = int(input('请输入周一收入'))
tue_income = int(input('请输入周二收入'))
wed_income = int(input('请输入周三收入'))
thur_income = int(input('请输入周四收入'))
fri_income = int(input('请输入周五收入'))
sat_income = int(input('请输入周六收入'))
sun_income = int(input('请输入周天收入'))
mon_expand = int(input('请输入周一支出'))
tue_expand = int(input('请输入周二支出'))
wed_expand = int(input('请输入周三支出'))
thur_expand = int(input('请输入周四支出'))
fri_expand = int(input('请输入周五支出'))
sat_expand = int(input('请输入周六支出'))
sun_expand = int(input('请输入周天支出'))
print('周一结余',mon_income-mon_expand)
print('周二结余',tue_income-tue_expand)
print('周三结余',wed_income-wed_expand)
print('周四结余',thur_income-thur_expand)
print('周五结余',fri_income-fri_expand)
print('周六结余',sat_income-sat_expand)
print('周天结余',sun_income-sun_expand)
print('最终结余',(mon_income-mon_expand)+(tue_income-tue_expand)+(wed_income-wed_expand)+(thur_income-thur_expand)+(fri_income-fri_expand)+(sat_income-sat_expand)+(sun_income-sun_expand))